package parser

import (
	"encoding/xml"
	"log"
	"net/http"

	"golang.org/x/net/html/charset"
)

// Parse xml
func Parse() *AutoGenerated {
	var autoGenerated AutoGenerated
	url := "http://news.rediff.com/commentary/2018/may/20/liveupdates.xml"
	// Build the request
	req, err := http.NewRequest("GET", url, nil)
	if err != nil {
		log.Fatal("NewRequest: ", err)
		return nil
	}

	// For control over HTTP client headers,
	// redirect policy, and other settings,
	// create a Client
	// A Client is an HTTP client
	client := &http.Client{}

	// Send the request via a client
	// Do sends an HTTP request and
	// returns an HTTP response
	resp, err := client.Do(req)
	if err != nil {
		log.Fatal("Do: ", err)
		return nil
	}

	// Callers should close resp.Body
	// when done reading from it
	// Defer the closing of the body
	defer resp.Body.Close()

	decoder := xml.NewDecoder(resp.Body)
	decoder.CharsetReader = charset.NewReaderLabel
	err = decoder.Decode(&autoGenerated)

	autoGenerated.Decode()

	return &autoGenerated

}
